### ISSUE TITLE
windows errors

### ISSUE THREAD

**Issue by zhangyaoci** [LuaLS/vscode-lua#104]
### Which OS are you using?

Windows

### Expected Behaviour

no error 

### Actual Behaviour

...

I also see the following error:

```
[2023-03-08 09:39:28] |   ERROR   |         Git        | error: cannot lock ref 'refs/remotes/origin/main': is at f7fa9f2fc086555343d6358aa127c1605dd8e00b but expected e9cfbce0b2381bcd653f956791a545d7a51e9449
From https://github.com/LuaLS/LLS-Addons
 ! e9cfbce..f7fa9f2  main       -> origin/main  (unable to update local ref)

```

### Reproduction steps

2. Click '...'
3. See error '...'

**Comment by carsakiller** [comment]
This is likely an issue resulting from an older version of the addon manager. Try deleting `/C:/Users/YOU/AppData/Roaming/Code/User/globalStorage/sumneko.lua/addonManager` and restarting VS Code

**Comment by carsakiller** [comment]
Closing stale issue
