### ISSUE TITLE
on open vscode

### ISSUE THREAD

**Issue by jamesynotnot** [LuaLS/vscode-lua#111]
### Which OS are you using?

MacOS

### Expected Behaviour

no error

### Actual Behaviour

...

I also see the following error:

```
[2023-03-09 10:35:46] |   ERROR   |         Git        | fatal: not a git repository (or any of the parent directories): .git

```

### Reproduction steps

2. Click '...'
3. See error '...'

**Comment by carsakiller** [comment]
Please see https://github.com/LuaLS/vscode-lua/issues/81 and confirm your version 🙂
