### ISSUE TITLE
Startup much slower

### ISSUE THREAD

**Issue by sumneko** [LuaLS/vscode-lua#114]
The startup time on my computer is about 300ms before, and now it takes more than 2000ms.
I haven't looked into it, but the probability reason is the addone manager.

Could you please take a look for it @carsakiller

**Comment by carsakiller** [comment]
I ran some tests across a bunch of versions in VS Code. It looks like startup time gets over three times as slow after the introduction of the addon manager 😳. Luckily, in the latest version it is somehow faster than ever.

| Version | Startup Time (ms) |
|:-------:|:-----------------:|
| 3.6.9   | 972               |
| 3.6.10  | 937               |
| 3.6.11  | 872               |
| 3.6.15  | 2675              |
| 3.6.16  | 2224              |
| 3.6.17  | 360               |

I believe the slowdown was from [checking if Git was installed on startup](https://github.com/LuaLS/vscode-lua/commit/5c95ccab22b0882c43e1bbd697f91fcf0ff78a6f#diff-4fc68ffef0339f7205a2786ffe2334a647050f5c5e546c3a04f411a0d134b108L27-L29). As of `v3.6.17`, that is only performed after the user runs the addon manager command, and it uses a different strategy. Still, it should only be *just* as fast as before, I am not sure why it is significantly faster than `v3.6.11`.

**Comment by carsakiller** [comment]
There may still be some improvements that can be made as well by packaging the client
