### ISSUE TITLE
Addon manager is broken

### ISSUE THREAD

**Issue by hertanion** [LuaLS/vscode-lua#116]
### How are you using the lua-language-server?

Visual Studio Code Extension (sumneko.lua)

### Which OS are you using?

Windows

### What is the issue affecting?

Libraries

### Expected Behaviour

There should be buttons to turn addons on and off.

### Actual Behaviour

There are no buttons to turn addons on and off.

### Reproduction steps

1. Go to 'Lua Addon Manager'
![image](https://user-images.githubusercontent.com/90708207/229596203-bbf4b6f5-f071-40c0-b1a6-9d2b222d357a.png)

### Additional Notes

Yesterday, the buttons were shown.

**Comment by carsakiller** [comment]
Hello 👋

Did you have a workspace open? You can only enable/disable addons in a workspace, so opening VS Code in "file only" mode could be the cause.

Otherwise, please include your log file to help debug. You can open the log file with the little page icon in the bottom right.

**Comment by hertanion** [comment]
No, it was launched without a workspace, launching in a workspace helped solve the problem. Thanks!
