### ISSUE TITLE
Unable to connect to addon manager

### ISSUE THREAD

**Issue by holipop** [LuaLS/vscode-lua#149]
### Which OS are you using?

MacOS

### Expected Behaviour

Opening the addon manager via the command palette and viewing the available addons.

### Actual Behaviour

Opening the addon manager gives this error:

```
[2024-09-29 03:37:59] |   ERROR   |     Filesystem     | Error: ENOTDIR: not a directory, stat '/Users/sunny/Library/Application Support/Code/User/globalStorage/sumneko.lua/addonManager/addons/.DS_Store/module'
```

The tab for the addon manager is stuck in this screen. I have a stable internet connection.
<img width="768" alt="Screenshot 2024-09-29 at 3 42 37 AM" src="https://github.com/user-attachments/assets/46652ac8-2bae-46b2-b188-07d2b753b352">

### Reproduction steps

1. Open the Command Palette
2. Select "Lua: Open Addon Manager"
3. Error is thrown and connection fails.

### Additional Notes

I've tried uninstalling the extension and reinstalling. I last remember this working earlier this year, so I'm unsure if an update caused this or something on my end. I can still use libraries by adding their path in my `library` field via .vscode/settings.json but don't seem to be able to update them. Thank you!

### Log

[03.log](https://github.com/user-attachments/files/17178605/03.log)

**Comment by carsakiller** [comment]
Hello 👋

This should be fixed in the latest release of the extension, `v3.11.0`, by https://github.com/LuaLS/vscode-lua/pull/147 🙂
