### ISSUE TITLE
problem with addons

### ISSUE THREAD

**Issue by fokichevskiy** [LuaLS/vscode-lua#153]
### Which OS are you using?

Windows

### Expected Behaviour

not working

### Actual Behaviour

I also see the following error with addons

```
[2024-10-20 20:24:24] |    WARN   |        Addon       | Failed to apply settings of "trilogyloader"
[2024-10-20 20:24:24] |    WARN   |        Addon       | [20:24:24.361][error][#0]: script\config\config.lua:136: unknown key: [lua]
stack traceback:
	[C]: in function 'assert'
	script\config\config.lua:136: in function 'config.config.prop'
	script\client.lua:536: in function 'client.setConfig'
	script\core\command\setConfig.lua:10: in function 'core.command.setConfig'
	(...tail calls...)
	[C]: in function 'xpcall'
	script\proto\proto.lua:202: in function <script\proto\proto.lua:177>
```

### Reproduction steps

1. Go to Addon Manager
2. Click Enable
3. See error

**Comment by carsakiller** [comment]
It appears that the `config.json` for that [addon is malformed](https://github.com/fokichevskiy/TrilogySnippets/blob/d87b71377618eacd25fc9de769d59942f9a7d1c2/config.json) and will need an update.

See the wiki for how it should be formatted: https://luals.github.io/wiki/addons/#configjson
