### ISSUE TITLE
Annotation completion details pane is too small

### ISSUE THREAD

**Issue by carsakiller** [LuaLS/vscode-lua#63]
When receiving completions for annotations, the details window that appears to offer info on completions is too narrow and it cuts off the text. The window can be resized manually but it appears to always default back to being too small when VS Code is restarted.
![windowResize](https://user-images.githubusercontent.com/61925890/179782354-df1efe12-6670-4a59-b4a4-9161efe339f1.gif)
Is there any way this can be adjusted? The dev that implemented the resizing feature [says it can be auto-resized](https://github.com/microsoft/vscode/pull/109094#issuecomment-714267025) but I haven't had any luck doing so.

I [found a comment](https://github.com/microsoft/vscode/issues/29126#issuecomment-715226442) from one of the VS Code devs that says font size and line height can be suggested, but nothing about suggested width 😕. This could just be a VS Code issue but maybe you know of a option that allows the width to be suggested?

**Comment by sumneko** [comment]
The late reply: I don't know

**Comment by carsakiller** [comment]
Looks like the manual resize will just have to do. From what I have read, it _should_ be saved across sessions.
