### ISSUE TITLE
Blurry description images, missing icons

### ISSUE THREAD

**Issue by C3pa** [LuaLS/vscode-lua#77]
The buttons at the top of the description have 2 issues:
1. build, and Average time to resolve an issue have missing icons
2. VS Marketplace, installs, and downloads buttons have blurry images

It looks like this in VSCode (inside red rectangle):
![image](https://user-images.githubusercontent.com/41503714/219851589-bf3e7c27-ca9c-4f07-a223-bbeb94ceb151.png)

Here is an example of a different plugin called Error Lens whose icons aren't blurry:
![image](https://user-images.githubusercontent.com/41503714/219851710-3b03d005-87f1-4564-b6c4-0045d98b16e2.png)
The comparisons above don't illustrate the issue best. I'd recommend opening both images in a new tab, still for an accurate comparison see the issues in VSCode.

The desired looks are obviously non-blurry icons and buttons with icons for the first described issue.

**Comment by carsakiller** [comment]
This is due to VS Code blocking all SVGs from non-verified domains for security reasons. Although, I thought the build SVG was from Github, which should be verified...

As for the blurry icons, they may be JPG fallbacks for VS Code, but I am not sure.

**Comment by sumneko** [comment]
We can just remove these 2 images after coping readme from lua-language-server to vscode-lua.
