### ISSUE TITLE
There is no description for the 'Addon manager' setting

### ISSUE THREAD

**Issue by serg3295** [LuaLS/vscode-lua#97]
### Which OS are you using?

Windows

### Expected Behaviour

Show description

### Actual Behaviour

![06-03-23_14-27](https://user-images.githubusercontent.com/75196080/223098615-a939b978-4eb9-4f1a-b421-58d75c32be4b.png)

### Reproduction steps

2. Click '...'
3. See error '...'

**Comment by carsakiller** [comment]
@sumneko is this a VS Code bug again or is it not generated from [`locale/en-us/setting.lua`](https://github.com/LuaLS/lua-language-server/blob/81cffaa48eded4761f6c0b3b2a355d6926b5053e/locale/en-us/setting.lua#L427)?

**Comment by sumneko** [comment]
> @sumneko is this a VS Code bug again or is it not generated from [`locale/en-us/setting.lua`](https://github.com/LuaLS/lua-language-server/blob/81cffaa48eded4761f6c0b3b2a355d6926b5053e/locale/en-us/setting.lua#L427)?

This is description for command, the setting should be `config.addonManager.enable`

**Comment by carsakiller** [comment]
Right 🥴
