### ISSUE TITLE
VS Code Lua Plugin

### ISSUE THREAD

**Issue by Jacques-Mock-Schindler** [LuaLS/vscode-lua#98]
### Which OS are you using?

Windows

### Expected Behaviour

nothing in particular

### Actual Behaviour

...

I also see the following error:

```
[2023-03-06 13:39:48] |   ERROR   |         Git        | error: The following untracked working tree files would be overwritten by checkout:
	.github/ISSUE_TEMPLATE/config.yml
	.github/ISSUE_TEMPLATE/new_addon.yml
	.github/PULL_REQUEST_TEMPLATE/newAddon.md
	.github/workflows/main.yml
	.gitmodules
	CONTRIBUTING.md
	LICENSE
	README.md
	addons/busted/info.json
	addons/cc-tweaked/info.json
	addons/cocos4.0/info.json
	addons/love2d/info.json
	addons/lovr/info.json
	addons/luaecs/info.json
	addons/luafilesystem/info.json
	addons/luassert/info.json
	addons/openresty/info.json
	addons/skynet/info.json
	schemas/addon_config.schema.json
	schemas/addon_info.schema.json
Please move or remove them before you switch branches.
Aborting

```

### Reproduction steps

just opening VS Code from the command line within a given folder

#### STARTUP ####
[2023-03-06 13:39:48] |   DEBUG   |     Filesystem     | Created directory at "/C:/Users/jcms/AppData/Roaming/Code/User/globalStorage/sumneko.lua/addonManager"
[2023-03-06 13:39:48] |   ERROR   |         Git        | Failed to checkout repo!
[2023-03-06 13:39:48] |   ERROR   |         Git        | error: The following untracked working tree files would be overwritten by checkout:
	.github/ISSUE_TEMPLATE/config.yml
	.github/ISSUE_TEMPLATE/new_addon.yml
	.github/PULL_REQUEST_TEMPLATE/newAddon.md
	.github/workflows/main.yml
	.gitmodules
	CONTRIBUTING.md
	LICENSE
	README.md
	addons/busted/info.json
	addons/cc-tweaked/info.json
	addons/cocos4.0/info.json
	addons/love2d/info.json
	addons/lovr/info.json
	addons/luaecs/info.json
	addons/luafilesystem/info.json
	addons/luassert/info.json
	addons/openresty/info.json
	addons/skynet/info.json
	schemas/addon_config.schema.json
	schemas/addon_info.schema.json
Please move or remove them before you switch branches.
Aborting

**Comment by carsakiller** [comment]
It seems that the files in `/C:/Users/jcms/AppData/Roaming/Code/User/globalStorage/sumneko.lua/addonManager` were modified. If you haven't made any changes you would like to keep, you can just delete the `addonManager` folder and the addon manager should re-initialize on next startup.

**Comment by Jacques-Mock-Schindler** [comment]
thanks - the error did not appear any more at startup
